### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by 0xzoz**
The readme was misleading for future contributors since changes were made. This will better direct first time contributors

### CODE REVIEW

**Review by mhluongo — APPROVED** [review]
🙌

**Comment by mhluongo** [comment]
@0xzoz this is good to merge, but we require signed commits! Let me if you need a guide to set it up

**Comment by henryboldi** [comment]
Also probably worth adding a commit message 🙏

**Comment by 0xzoz** [comment]
Thanks for the heads up @mhluongo and @henryboldi. Should be good to go.

**Comment by henryboldi** [comment]
Thank you! I believe you've still got to upload your key to GH for it to be recognized as verified. @0xzoz

**Comment by 0xzoz** [comment]
Added @henryboldi. Do I need to do anything else on my end?

**Pull request merged**
